-- MySQL Script generated by MySQL Workbench
-- seg 25 mai 2020 18:22:55 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaGerenciaDeUsuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaGerenciaDeUsuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaGerenciaDeUsuarios` ;
USE `sistemaGerenciaDeUsuarios` ;

-- -----------------------------------------------------
-- Table `sistemaGerenciaDeUsuarios`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGerenciaDeUsuarios`.`Cargos` (
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGerenciaDeUsuarios`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGerenciaDeUsuarios`.`perfis` (
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGerenciaDeUsuarios`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGerenciaDeUsuarios`.`usuarios` (
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `Cargos_nome` VARCHAR(45) NOT NULL,
  `perfis_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `Cargos_nome`, `perfis_nome`),
  INDEX `fk_usuarios_Cargos_idx` (`Cargos_nome` ASC) VISIBLE,
  INDEX `fk_usuarios_perfis1_idx` (`perfis_nome` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_Cargos`
    FOREIGN KEY (`Cargos_nome`)
    REFERENCES `sistemaGerenciaDeUsuarios`.`Cargos` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_perfis1`
    FOREIGN KEY (`perfis_nome`)
    REFERENCES `sistemaGerenciaDeUsuarios`.`perfis` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
